services:
    app_bundle.registration_confirmation_listener:
        class: AppBundle\EventListener\RegistrationConfirmationListener
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - { name: kernel.event_subscriber }
    fos_user.doctrine_registry:
        alias: doctrine
